name              'emacs'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs emacs'
version           '0.11.12'
source_url        'https://github.com/sous-chefs/emacs'
issues_url        'https://github.com/sous-chefs/emacs/issues'

supports 'ubuntu'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'fedora'
supports 'arch'
supports 'freebsd'
